# Generated by Django 5.2.12 on 2026-03-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requires_profile_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='requires_profile_update',
            field=models.BooleanField(default=False),
        ),
    ]
