# Generated by Django 5.2.12 on 2026-03-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0002_customuser_requires_profile_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=50)),
                ('rx_bytes', models.BigIntegerField()),
                ('tx_bytes', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
