# Generated by Django 6.0.3 on 2026-03-26 09:02

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0004_remove_customuser_plan_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
            ],
            options={
                'verbose_name': 'Sổ quản lý Gói cước',
                'verbose_name_plural': 'Sổ quản lý Gói cước',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vpn_panel.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VPNConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Cấu hình VPN',
                'verbose_name_plural': 'Cấu hình VPN',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vpn_panel.setting',),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
    ]
