# Generated by Django 6.0.3 on 2026-03-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0005_subscription_vpnconfig_alter_customuser_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='student_class',
        ),
    ]
