# Generated by Django 6.0.3 on 2026-03-26 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0006_remove_customuser_student_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='duration_days',
            field=models.IntegerField(default=30, verbose_name='Số ngày mua'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='duration_days',
            field=models.IntegerField(default=30, verbose_name='Số ngày mua'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày mua'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày mua'),
        ),
    ]
