# Generated by Django 6.0.3 on 2026-03-26 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0007_customuser_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày mua'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày mua'),
        ),
    ]
