# Generated by Django 6.0.3 on 2026-03-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0008_alter_customuser_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('EXPIRED', 'Hết hạn'), ('CANCELED', 'Đã hủy'), ('DEMO', 'Dùng thử (3 ngày)')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('EXPIRED', 'Hết hạn'), ('CANCELED', 'Đã hủy'), ('DEMO', 'Dùng thử (3 ngày)')], default='ACTIVE', max_length=20),
        ),
    ]
