# Generated by Django 6.0.3 on 2026-03-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0009_customuser_status_historicalcustomuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='duration_days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Duration (Days)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='duration_days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Duration (Days)'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
    ]
