# Generated by Django 6.0.3 on 2026-03-26 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0010_alter_customuser_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='duration_days',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Duration (Days)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='purchase_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='duration_days',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Duration (Days)'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='purchase_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Purchase Date'),
        ),
    ]
