# Generated by Django 6.0.3 on 2026-03-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0011_alter_customuser_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription Manager', 'verbose_name_plural': 'Subscription Manager'},
        ),
        migrations.AlterModelOptions(
            name='vpnconfig',
            options={'verbose_name': 'VPN Configuration', 'verbose_name_plural': 'VPN Configurations'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled'), ('DEMO', 'Demo (3 days)')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled'), ('DEMO', 'Demo (3 days)')], default='ACTIVE', max_length=20),
        ),
    ]
