# Generated by Django 6.0.3 on 2026-03-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0012_alter_subscription_options_alter_vpnconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content (HTML supported)')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Thông báo Email',
                'verbose_name_plural': 'Thông báo Email',
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Sổ quản lý Gói cước', 'verbose_name_plural': 'Sổ quản lý Gói cước'},
        ),
        migrations.AlterModelOptions(
            name='vpnconfig',
            options={'verbose_name': 'Cấu hình VPN', 'verbose_name_plural': 'Cấu hình VPN'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('EXPIRED', 'Hết hạn'), ('CANCELED', 'Đã hủy'), ('DEMO', 'Dùng thử (3 ngày)')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('EXPIRED', 'Hết hạn'), ('CANCELED', 'Đã hủy'), ('DEMO', 'Dùng thử (3 ngày)')], default='ACTIVE', max_length=20),
        ),
    ]
