# Generated by Django 6.0.3 on 2026-03-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0013_announcement_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Thành công'), ('FAILURE', 'Thất bại'), ('RUNNING', 'Đang chạy')], default='RUNNING', max_length=20)),
                ('result', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lịch sử Tác vụ',
                'verbose_name_plural': 'Lịch sử Tác vụ (Debug)',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.CreateModel(
            name='TaskControl',
            fields=[
            ],
            options={
                'verbose_name': 'Điều khiển Tác vụ',
                'verbose_name_plural': 'Điều khiển Tác vụ (Debug)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vpn_panel.tasklog',),
        ),
    ]
