# Generated by Django 6.0.3 on 2026-03-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0014_tasklog_alter_announcement_options_taskcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
            ],
            options={
                'verbose_name': 'Nhật ký Hệ thống',
                'verbose_name_plural': 'Nhật ký Hệ thống (Logs)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vpn_panel.tasklog',),
        ),
    ]
