# Generated by Django 6.0.3 on 2026-04-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0015_systemlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='openvpn_installer/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tệp Cài đặt',
                'verbose_name_plural': 'Tệp Cài đặt',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallerManager',
            fields=[
            ],
            options={
                'verbose_name': 'Quản lý Installer',
                'verbose_name_plural': 'Quản lý Installer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vpn_panel.setting',),
        ),
    ]
