# Generated by Django 6.0.3 on 2026-04-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_panel', '0016_installerfile_installermanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('EXPIRED', 'Hết hạn'), ('CANCELED', 'Đã hủy'), ('DEMO', 'Dùng thử (1 ngày)')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('EXPIRED', 'Hết hạn'), ('CANCELED', 'Đã hủy'), ('DEMO', 'Dùng thử (1 ngày)')], default='ACTIVE', max_length=20),
        ),
    ]
